[workspace]
resolver = "2"
members = [
    "crates/graphgarden-protocol",
    "crates/graphgarden-core",
    "crates/graphgarden",
]

[workspace.package]
edition = "2024"
license = "MIT"
repository = "https://github.com/bruits/graphgarden"
